# Weather EDA

In [1]:
import pandas as pd

In [23]:
df = pd.read_csv('final_proj_weather_data.csv')

In [24]:
df.head()

,STATION,DATE,AWND,FMTM,PGTM,PRCP,TMAX,TMIN
0,NaN,NaN,Average Daily Wind Speed (tenths of meters per...,Minute with highest wind speed (HHMM),Peak Gust Time (HHMM),Precipitation (tenths of mm),Max temp (tenths of degrees celsius),Min Temp (tenths of degrees celsius)
1,USW00014819,2001-01-01,33,1519,1518,0,-33,-106
2,USW00014819,2001-01-02,39,1616,1614,0,-67,-139
3,USW00014819,2001-01-03,54,1101,1100,0,-22,-139
4,USW00014819,2001-01-04,54,1951,1817,0,0,-50

In [25]:
df = df.drop(0)
df.head()

       STATION        DATE AWND  FMTM  PGTM PRCP TMAX  TMIN
1  USW00014819  2001-01-01   33  1519  1518    0  -33  -106
2  USW00014819  2001-01-02   39  1616  1614    0  -67  -139
3  USW00014819  2001-01-03   54  1101  1100    0  -22  -139
4  USW00014819  2001-01-04   54  1951  1817    0    0   -50
5  USW00014819  2001-01-05   59  1458  1132    0   28   -56

In [30]:
df.isnull().sum()

STATION       0
DATE          0
AWND          8
FMTM       5068
PGTM        163
PRCP         11
TMAX          2
TMIN          2
dtype: int64

In [35]:
df = df.astype({'DATE': 'datetime64', 'AWND':'float32', 'FMTM':'float32', 'PGTM':'float32','PRCP':'float32','TMAX':'float32','TMIN':'float32'})

//anaconda/lib/python3.6/site-packages/pandas/core/internals.py:3224: FutureWarning: Passing in 'datetime64' dtype with no frequency is deprecated and will raise in a future version. Please pass in 'datetime64[ns]' instead.
  return self.apply('astype', dtype=dtype, **kwargs)

In [36]:
df.dtypes

STATION            object
DATE       datetime64[ns]
AWND              float32
FMTM              float32
PGTM              float32
PRCP              float32
TMAX              float32
TMIN              float32
dtype: object

In [37]:
df = df.fillna(df.median())

In [38]:
df.isnull().sum()

STATION    0
DATE       0
AWND       0
FMTM       0
PGTM       0
PRCP       0
TMAX       0
TMIN       0
dtype: int64

In [48]:
df.describe()

,AWND,FMTM,PGTM,PRCP,TMAX,TMIN,AvgWindSpeed-MPH,Precipitation-IN,MaxTemp-F,MinTemp-F
count,6892.000000,6892.000000,6892.000000,6892.000000,6892.000000,6892.000000,6892.000000,6892.000000,6892.000000,6892.000000
mean,43.780617,1424.299316,1346.379761,24.589378,157.451248,68.233315,97.934547,0.968084,60.341206,44.281906
std,15.805634,296.962830,581.572510,71.467323,117.248650,106.274071,35.356335,2.813741,21.104742,19.129337
min,8.000000,0.000000,0.000000,0.000000,-227.000000,-299.000000,17.895519,0.000000,-8.860001,-21.820000
25%,32.000000,1443.000000,1106.750000,0.000000,61.000000,-10.000000,71.582077,0.000000,42.980000,30.200001
50%,42.000000,1443.000000,1414.000000,0.000000,167.000000,72.000000,93.951477,0.000000,62.060001,44.959999
75%,53.000000,1443.000000,1704.000000,10.000000,261.000000,161.000000,118.557816,0.393701,78.979996,60.980000
max,125.000000,2359.000000,2359.000000,1321.000000,400.000000,283.000000,279.617493,52.007874,104.000000,82.940002

In [49]:
df["AvgWindSpeed-MPH"] = (df["AWND"] / 10) * 2.23694

In [50]:
df["Precipitation-IN"] = (df["PRCP"]/10) /25.4

In [51]:
df["MaxTemp-F"] = (df["TMAX"] / 10) * 1.8 + 32
df["MinTemp-F"] = (df["TMIN"] / 10) * 1.8 + 32

In [52]:
df.head()

,STATION,DATE,AWND,FMTM,PGTM,PRCP,TMAX,TMIN,AvgWindSpeed-MPH,Precipitation-IN,MaxTemp-F,MinTemp-F
1,USW00014819,2001-01-01,33.0,1519.0,1518.0,0.0,-33.0,-106.0,7.381902,0.0,26.060001,12.920000
2,USW00014819,2001-01-02,39.0,1616.0,1614.0,0.0,-67.0,-139.0,8.724066,0.0,19.940001,6.980001
3,USW00014819,2001-01-03,54.0,1101.0,1100.0,0.0,-22.0,-139.0,12.079475,0.0,28.040001,6.980001
4,USW00014819,2001-01-04,54.0,1951.0,1817.0,0.0,0.0,-50.0,12.079475,0.0,32.000000,23.000000
5,USW00014819,2001-01-05,59.0,1458.0,1132.0,0.0,28.0,-56.0,13.197946,0.0,37.040001,21.920000

In [53]:
df.describe()

,AWND,FMTM,PGTM,PRCP,TMAX,TMIN,AvgWindSpeed-MPH,Precipitation-IN,MaxTemp-F,MinTemp-F
count,6892.000000,6892.000000,6892.000000,6892.000000,6892.000000,6892.000000,6892.000000,6892.000000,6892.000000,6892.000000
mean,43.780617,1424.299316,1346.379761,24.589378,157.451248,68.233315,9.793484,0.096809,60.341206,44.281906
std,15.805634,296.962830,581.572510,71.467323,117.248650,106.274071,3.535626,0.281371,21.104742,19.129337
min,8.000000,0.000000,0.000000,0.000000,-227.000000,-299.000000,1.789552,0.000000,-8.860001,-21.820000
25%,32.000000,1443.000000,1106.750000,0.000000,61.000000,-10.000000,7.158208,0.000000,42.980000,30.200001
50%,42.000000,1443.000000,1414.000000,0.000000,167.000000,72.000000,9.395147,0.000000,62.060001,44.959999
75%,53.000000,1443.000000,1704.000000,10.000000,261.000000,161.000000,11.855782,0.039370,78.979996,60.980000
max,125.000000,2359.000000,2359.000000,1321.000000,400.000000,283.000000,27.961748,5.200788,104.000000,82.940002

In [63]:
df["WindBins"] = df.apply(lambda x: 'L' if x['AvgWindSpeed-MPH'] < 7.2 else ('M' if x['AvgWindSpeed-MPH'] < 11.9 else 'H'), axis=1)
df["HighTempBins"] = df.apply(lambda x: 'L' if x['MaxTemp-F'] < 43 else ('M' if x['MaxTemp-F'] < 79 else 'H'), axis=1)
df["PrecipitationBins"] = df.apply(lambda x: 'L' if x['Precipitation-IN'] < 0.04 else "H", axis=1)

In [64]:
df.head()

,STATION,DATE,AWND,FMTM,PGTM,PRCP,TMAX,TMIN,AvgWindSpeed-MPH,Precipitation-IN,MaxTemp-F,MinTemp-F,WindBins,HighTempBins,PrecipitationBins
1,USW00014819,2001-01-01,33.0,1519.0,1518.0,0.0,-33.0,-106.0,7.381902,0.0,26.060001,12.920000,M,L,L
2,USW00014819,2001-01-02,39.0,1616.0,1614.0,0.0,-67.0,-139.0,8.724066,0.0,19.940001,6.980001,M,L,L
3,USW00014819,2001-01-03,54.0,1101.0,1100.0,0.0,-22.0,-139.0,12.079475,0.0,28.040001,6.980001,H,L,L
4,USW00014819,2001-01-04,54.0,1951.0,1817.0,0.0,0.0,-50.0,12.079475,0.0,32.000000,23.000000,H,L,L
5,USW00014819,2001-01-05,59.0,1458.0,1132.0,0.0,28.0,-56.0,13.197946,0.0,37.040001,21.920000,H,L,L